# Local CPU Testing Configuration
# This config is designed for local testing without GPU requirements

# Model configuration
model:
  name: "google/flan-t5-base"
  strategy: "lora"  # or "full" for full fine-tuning
  lora_config:
    r: 8
    lora_alpha: 16
    target_modules: ["q", "v"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "SEQ_2_SEQ_LM"

# Dataset configuration
dataset:
  name: "BioLaySumm/BioLaySumm2025-LaymanRRG-opensource-track"
  max_samples: 10  # Very small for local testing
  max_length: 128  # Shorter sequences for speed
  train_split: "train"
  val_split: "validation"
  test_split: "test"

# Training configuration (CPU-optimized)
training:
  epochs: 1
  batch_size: 1  # Small batch for CPU
  learning_rate: 1e-4
  weight_decay: 0.01
  max_grad_norm: 1.0
  warmup_steps: 10
  max_steps: 5  # Very few steps for testing
  logging_steps: 1
  eval_steps: 3
  save_steps: 5
  eval_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: false
  report_to: "none"  # Disable wandb/tensorboard for local testing
  gradient_accumulation_steps: 1
  dataloader_num_workers: 0  # Avoid multiprocessing issues on Windows
  remove_unused_columns: false
  seed: 42

# Output configuration
output:
  root_dir: "reports/local_test"
  project_name: "local_cpu_test"
  save_config: true
  save_logs: true
