# T5-small Full Fine-Tuning Local Test Configuration
# Minimal test for local validation before cluster deployment

# Dataset Configuration
dataset:
  name: "BioLaySumm/BioLaySumm2025-LaymanRRG-opensource-track"
  max_source_length: 128      # Shorter for local test
  max_target_length: 64       # Shorter for local test
  seed: 42
  local_data_path: null

# Model Configuration
model:
  name: "t5-small"            # T5-small for full fine-tuning
  torch_dtype: "bfloat16"

# Training Configuration
training:
  strategy: "full"            # Full fine-tuning strategy
  batch_size: 1               # Small batch for local test
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  num_epochs: 1               # Just 1 epoch for test
  warmup_steps: 10
  weight_decay: 0.01
  max_grad_norm: 1.0
  
  # Evaluation and logging
  eval_steps: 5
  save_steps: 10
  logging_steps: 2
  eval_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: false
  report_to: "none"           # Disable logging for local test
  
  # Reproducibility
  seed: 42
  data_seed: 42
  
  # Performance
  dataloader_num_workers: 0   # No multiprocessing for local test
  remove_unused_columns: false
  
  # Mixed precision
  bf16: false                 # Disable for local test
  fp16: false

# Full Fine-Tuning Configuration
full_finetuning:
  enabled: true
  gradient_checkpointing: false  # Disable for local test

# Output Configuration
output:
  root_dir: "reports/local_test"
  project_name: "t5-small-full-local-test"
  save_config: false
  save_logs: false

# Reproducibility Configuration
reproducibility:
  seed: 42
  data_seed: 42
  model_seed: 42

# Hardware Configuration
hardware:
  dataloader_num_workers: 0
  pin_memory: false
  gradient_checkpointing: false

# Evaluation Configuration
evaluation:
  max_new_tokens: 64
  num_beams: 2
  length_penalty: 0.6
  no_repeat_ngram_size: 3
  early_stopping: true
