# Ultra-Fast Test Configuration (15 minutes max)
# This config is designed for the fastest possible validation run

# Model configuration
model:
  name: "google/flan-t5-base"
  strategy: "lora"
  lora_config:
    r: 8
    lora_alpha: 16
    target_modules: ["q", "v"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "SEQ_2_SEQ_LM"

# Dataset configuration - TINY for speed
dataset:
  name: "BioLaySumm/BioLaySumm2025-LaymanRRG-opensource-track"
  max_samples: 20  # Only 20 samples!
  max_length: 64   # Very short sequences
  train_split: "train"
  val_split: "validation"
  test_split: "test"

# Training configuration - MINIMAL
training:
  epochs: 1
  batch_size: 2    # Small batch
  learning_rate: 1e-4
  weight_decay: 0.01
  max_grad_norm: 1.0
  warmup_steps: 2  # Minimal warmup
  max_steps: 5     # Only 5 training steps!
  logging_steps: 1
  eval_steps: 3
  save_steps: 5
  eval_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: false
  report_to: "none"  # Disable all logging
  gradient_accumulation_steps: 1
  dataloader_num_workers: 0  # No multiprocessing
  remove_unused_columns: false
  seed: 42
  bf16: false  # Disable mixed precision for speed

# Output configuration
output:
  root_dir: "reports/ultra_fast_test"
  project_name: "ultra_fast_test"
  save_config: false  # Don't save config
  save_logs: false    # Don't save logs
