# .github/workflows/readme-pdf.yml
name: Export README to PDF

on:
  push:
    branches: [ pdf ]     # change this
    paths:
      - 'recognition/layrad-flant5-lora-nchung/README.md'
      - '.github/workflows/readme-pdf.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF
        run: |
          docker run --rm -v "${{ github.workspace }}:/data" pandoc/latex:latest \
            recognition/layrad-flant5-lora-nchung/README.md -f gfm -o README.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: readme-pdf
          path: README.pdf
